USE [master]
GO

/****** Object:  Database [BoatRental]    Script Date: 16-09-2020 11:47:16 PM ******/
CREATE DATABASE [BoatRental]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BoatRental', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BoatRental.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BoatRental_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BoatRental_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BoatRental].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BoatRental] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BoatRental] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BoatRental] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BoatRental] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BoatRental] SET ARITHABORT OFF 
GO

ALTER DATABASE [BoatRental] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BoatRental] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BoatRental] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BoatRental] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BoatRental] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BoatRental] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BoatRental] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BoatRental] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BoatRental] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BoatRental] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BoatRental] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BoatRental] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BoatRental] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BoatRental] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BoatRental] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BoatRental] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BoatRental] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BoatRental] SET RECOVERY FULL 
GO

ALTER DATABASE [BoatRental] SET  MULTI_USER 
GO

ALTER DATABASE [BoatRental] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BoatRental] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BoatRental] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BoatRental] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BoatRental] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BoatRental] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BoatRental] SET  READ_WRITE 
GO


